### PR TITLE
made changes in the license

### PR DESCRIPTION
**Pull request by SudoSu-bham**
Corrected the changes made in the license of the activity

### CODE REVIEW

**Comment by SudoSu-bham** [comment]
cc @tchx84

**Review by tchx84 — CHANGES_REQUESTED** [review]
Check the CI failure messages, we probably need to find the proper string for MIT license among other things it's complaining now...

**Comment by SudoSu-bham** [comment]
[Some application](https://github.com/flathub/org.godotengine.GodotSharp/blob/f522219db1d263864cdf5dbff547095bc5befd5d/org.godotengine.GodotSharp.appdata.xml#L34) are using `MIT` string to depict the `MIT License`. I tested `MathHurdler` with only `MIT` as license string and there was no linter error. 
Also we can refer [spdx.org](https://spdx.org/licenses/) for `MIT License` they have mentioned `MIT` as identifier.

**Comment by tchx84** [comment]
> [Some application](https://github.com/flathub/org.godotengine.GodotSharp/blob/f522219db1d263864cdf5dbff547095bc5befd5d/org.godotengine.GodotSharp.appdata.xml#L34) are using `MIT` string to depict the `MIT License`. I tested `MathHurdler` with only `MIT` as license string and there was no linter error. Also we can refer [spdx.org](https://spdx.org/licenses/) for `MIT License` they have mentioned `MIT` as identifier.

okay, and can you fix it here?

**Review by tchx84 — APPROVED** [review]

**Pull request merged**
